# Generated by Django 5.2.2 on 2026-08-07 09:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('fen', models.CharField(max_length=100)),
                ('turn', models.CharField(choices=[('w', 'White to play'), ('b', 'Black to play')], default='w', max_length=1)),
                ('solution', models.TextField(help_text="Moves in SAN, space separated, e.g. 'Rxh2+ Kxh2 Rh8#'", validators=[django.core.validators.RegexValidator(message="Solution must be valid SAN moves, like 'Rxh2+ Kxh2 Rh8#'", regex='^([PNBRQK]?[a-h]?[1-8]?x?[a-h][1-8](=[NBRQ])?[+#]?\\.?\\s*)+$')])),
                ('hint', models.CharField(blank=True, help_text='Optional custom hint shown to the user. If left blank, the Hint button will just reveal the next correct move.', max_length=255)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily chess puzzle',
                'verbose_name_plural': 'Daily chess puzzles',
            },
        ),
        migrations.CreateModel(
            name='DailyPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_entries', to='news.chesspuzzle')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
