# Generated by Django 5.2.2 on 2026-08-17 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chesspuzzle',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='chesspuzzlesolve',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='chesspuzzlesolve',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chesspuzzle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chesspuzzle',
            name='player1',
            field=models.CharField(blank=True, default='Player 1', max_length=150),
        ),
        migrations.AddField(
            model_name='chesspuzzle',
            name='player2',
            field=models.CharField(blank=True, default='Player 2', max_length=150),
        ),
        migrations.AddField(
            model_name='chesspuzzle',
            name='source_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chesspuzzle',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='chesspuzzle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chesspuzzlesolve',
            name='hints_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chesspuzzle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='chesspuzzle',
            name='hint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chesspuzzle',
            name='move_explanations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='chesspuzzle',
            name='solution',
            field=models.TextField(help_text='Space separated SAN moves.'),
        ),
        migrations.AlterField(
            model_name='chesspuzzle',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='chesspuzzlesolve',
            name='time_taken',
            field=models.PositiveIntegerField(blank=True, help_text='Seconds', null=True),
        ),
        migrations.AlterField(
            model_name='chesspuzzlesolve',
            name='wrong_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='chesspuzzlesolve',
            constraint=models.UniqueConstraint(fields=('user', 'daily_puzzle'), name='unique_user_daily_puzzle'),
        ),
    ]
