# Generated by Django 5.2.2 on 2026-08-07 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_chesspuzzle_dailypuzzle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessPuzzleSolve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved_at', models.DateTimeField(auto_now_add=True)),
                ('time_taken', models.IntegerField(blank=True, help_text='Seconds', null=True)),
                ('made_mistake', models.BooleanField(default=False)),
                ('wrong_attempts', models.IntegerField(default=0)),
                ('daily_puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solves', to='news.dailypuzzle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chess_puzzle_solves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily puzzle solve',
                'verbose_name_plural': 'Daily puzzle solves',
                'unique_together': {('user', 'daily_puzzle')},
            },
        ),
    ]
