# Generated by Django 5.2.2 on 2025-06-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AddField(
            model_name='article',
            name='is_big_news',
            field=models.BooleanField(default=False),
        ),
    ]
