# Generated by Django 5.2.2 on 2026-09-04 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_chesspuzzle_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('GM', 'Grandmaster'), ('IM', 'International Master'), ('FM', 'FIDE Master'), ('CM', 'Candidate Master'), ('WGM', 'Woman Grandmaster'), ('WIM', 'Woman International Master'), ('WFM', 'Woman FIDE Master'), ('NM', 'National Master'), ('', 'No title')], max_length=4)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(help_text='e.g. Head Coach, Openings Specialist', max_length=120)),
                ('rating', models.PositiveSmallIntegerField(help_text='Current FIDE rating', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3500)])),
                ('bio', models.TextField(max_length=600)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='coaches/')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first on the coaches page')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coach',
                'verbose_name_plural': 'Coaches',
                'ordering': ['order', '-rating'],
            },
        ),
    ]
