# Generated by Django 5.2.2 on 2026-09-04 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('fide_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3500)])),
                ('fide_title', models.CharField(blank=True, choices=[('GM', 'Grandmaster'), ('IM', 'International Master'), ('FM', 'FIDE Master'), ('CM', 'Candidate Master'), ('WGM', 'Woman Grandmaster'), ('WIM', 'Woman International Master'), ('WFM', 'Woman FIDE Master'), ('NM', 'National Master'), ('', 'No title')], max_length=4)),
                ('playing_history', models.TextField(blank=True, help_text='Notable tournaments, achievements')),
                ('coaching_experience', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Coach Application',
                'verbose_name_plural': 'Coach Applications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
