# Generated by Django 5.2.2 on 2026-09-04 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_coachapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachapplication',
            name='created_coach',
            field=models.OneToOneField(blank=True, help_text='Coach profile auto-created when this application was accepted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='news.coach'),
        ),
    ]
