# Generated by Django 5.2.2 on 2025-06-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_article_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopPlayerImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fide_id', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='player_images/')),
            ],
        ),
    ]
