# Generated by Django 5.2.2 on 2025-06-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_topplayerimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topplayerimg',
            name='image',
            field=models.ImageField(null=True, upload_to='player_images/'),
        ),
    ]
