# Generated by Django 5.2.2 on 2025-06-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_tournamentbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BangladeshiTopPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bangladesh_players/')),
                ('fide_rating', models.PositiveIntegerField()),
                ('rank', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], unique=True)),
            ],
        ),
    ]
