# Generated by Django 5.2.2 on 2025-07-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_puzzle'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='turn',
            field=models.CharField(choices=[('w', 'White to play'), ('b', 'Black to play')], default='w', max_length=1),
        ),
    ]
