# Generated by Django 5.2.2 on 2025-07-07 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_puzzle_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='solution',
            field=models.TextField(help_text="Moves in SAN, like 'Rxh2+ Kxh2 Rh8#'", validators=[django.core.validators.RegexValidator(message="Solution must be valid SAN moves, like 'Rxh2+ Kxh2 Rh8#'", regex='^([PNBRQK]?[a-h]?[1-8]?x?[a-h][1-8](=[NBRQ])?[+#]?\\.?\\s*)+$')]),
        ),
    ]
