# Generated by Django 5.2.2 on 2025-07-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_alter_puzzle_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='show_profile',
            field=models.BooleanField(default=False, help_text='Show profile card'),
        ),
    ]
