# Generated by Django 5.2.2 on 2025-07-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_puzzle_show_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='show_profile',
            field=models.BooleanField(default=False),
        ),
    ]
