# Generated by Django 5.2.2 on 2025-07-09 05:28

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='show_profile',
        ),
        migrations.AddField(
            model_name='puzzle',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.quote'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='Quote',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
