# Generated by Django 5.2.2 on 2025-07-09 06:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_puzzlesolve'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzlesolve',
            old_name='puzzle',
            new_name='solve_puzzle',
        ),
        migrations.AlterUniqueTogether(
            name='puzzlesolve',
            unique_together={('user', 'solve_puzzle')},
        ),
    ]
