# Generated by Django 5.2.2 on 2025-07-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_rename_puzzle_puzzlesolve_solve_puzzle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzlesolve',
            name='time_taken',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
