# Generated by Django 5.2.2 on 2025-07-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='payment_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trx_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction ID'),
        ),
    ]
