# Generated by Django 5.2.2 on 2025-08-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0027_boardvision'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzlesolve',
            name='made_mistake',
            field=models.BooleanField(default=False),
        ),
    ]
