# Generated by Django 5.2.2 on 2025-08-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0028_puzzlesolve_made_mistake'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzlesolve',
            name='wrong_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
