# Generated by Django 5.2.2 on 2025-08-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0030_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/user.png', null=True, upload_to='profile_images/'),
        ),
    ]
