# Generated by Django 5.2.2 on 2025-08-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0031_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, default='Add Description Here', max_length=200, null=True),
        ),
    ]
