# Generated by Django 5.2.2 on 2025-09-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0034_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='free_premium_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='trx_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
