# Generated by Django 5.2.2 on 2025-10-06 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0035_userprofile_free_premium_start_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='link',
            field=models.URLField(default='https://example.com', max_length=500),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('REGULAR', 'Regular'), ('VIP', 'VIP'), ('ONLINE', 'Online Viewer')], default='REGULAR', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('ticket_code', models.CharField(editable=False, max_length=12, unique=True)),
                ('is_checked_in', models.BooleanField(default=False)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='news.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchase_date'],
                'unique_together': {('user', 'tournament', 'ticket_type')},
            },
        ),
    ]
