# Generated by Django 5.2.2 on 2025-12-02 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0037_move_alter_ticket_ticket_type_movecomment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movecomment',
            name='move',
        ),
        migrations.RemoveField(
            model_name='movecomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='uploadedgame',
            name='uploaded_by',
        ),
        migrations.DeleteModel(
            name='Move',
        ),
        migrations.DeleteModel(
            name='MoveComment',
        ),
        migrations.DeleteModel(
            name='UploadedGame',
        ),
    ]
