# Generated by Django 5.2.2 on 2025-12-02 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0039_move_movecomment_uploadedgame_move_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movecomment',
            name='move',
        ),
        migrations.RemoveField(
            model_name='movecomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Move',
        ),
        migrations.DeleteModel(
            name='MoveComment',
        ),
    ]
