# Generated by Django 5.2.2 on 2025-12-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0040_remove_movecomment_move_remove_movecomment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedgame',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
