# Generated by Django 5.2.2 on 2025-12-02 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0043_uploadedgame_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedgame',
            name='slug',
        ),
    ]
