# Generated by Django 5.2.2 on 2025-12-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0044_remove_uploadedgame_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedgame',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
