# Generated by Django 5.2.2 on 2025-12-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0045_uploadedgame_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedgame',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
