# Generated by Django 5.2.2 on 2025-12-02 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0046_alter_uploadedgame_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedgame',
            old_name='slug',
            new_name='slug_link',
        ),
    ]
