# Generated by Django 5.2.2 on 2025-12-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0048_gamecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecomment',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
