# Generated by Django 5.2.2 on 2025-12-06 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0049_gamecomment_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecomment',
            name='like_count',
        ),
    ]
