# Generated by Django 5.2.2 on 2025-12-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0050_remove_gamecomment_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedgame',
            name='black_player',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadedgame',
            name='white_player',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
