# Generated by Django 5.2.2 on 2026-02-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0053_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentbanner',
            name='inside_home',
            field=models.BooleanField(default=False),
        ),
    ]
