# Generated by Django 5.2.2 on 2026-02-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0054_tournamentbanner_inside_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedgame',
            old_name='pgn',
            new_name='pgn_text',
        ),
        migrations.AddField(
            model_name='uploadedgame',
            name='pgn_file',
            field=models.FileField(blank=True, null=True, upload_to='pgn_files/'),
        ),
    ]
