# Generated by Django 5.2.2 on 2026-02-28 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0055_rename_pgn_uploadedgame_pgn_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedgame',
            old_name='pgn_text',
            new_name='pgn',
        ),
        migrations.RemoveField(
            model_name='uploadedgame',
            name='pgn_file',
        ),
    ]
