# Generated by Django 5.2.2 on 2026-03-18 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0057_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='news.events'),
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
