# Generated by Django 5.2.2 on 2026-03-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0058_alter_ticket_tournament_delete_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
