# Generated by Django 5.2.2 on 2026-03-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0060_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
