# Generated by Django 5.2.2 on 2026-04-03 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0062_memoryposition_memoryresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memoryposition',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='memoryposition',
            name='difficulty',
        ),
        migrations.DeleteModel(
            name='MemoryResult',
        ),
    ]
