# Generated by Django 5.2.2 on 2026-04-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0063_remove_memoryposition_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryposition',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='memoryposition',
            name='game_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
