# Generated by Django 5.2.2 on 2026-04-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0064_memoryposition_difficulty_memoryposition_game_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bangladeshitopplayer',
            name='rank',
        ),
        migrations.AddField(
            model_name='bangladeshitopplayer',
            name='fide_id',
            field=models.CharField(default=1200, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
