# Generated by Django 5.2.2 on 2026-04-10 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0065_remove_bangladeshitopplayer_rank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bangladeshitopplayer',
            name='fide_rating',
        ),
    ]
