# Generated by Django 5.2.2 on 2026-04-18 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0066_remove_bangladeshitopplayer_fide_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(choices=[('mother', "What is your mother's maiden name?"), ('pet', 'What was the name of your first pet?'), ('city', 'What city were you born in?'), ('school', 'What was the name of your primary school?'), ('friend', 'What is the name of your childhood best friend?'), ('food', 'What is your favourite food?'), ('teacher', "What was your favourite teacher's name?"), ('car', 'What was the model of your first car or bicycle?'), ('chess', 'What is your favourite chess opening?')], max_length=20)),
                ('answer', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_question', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
