# Generated by Django 5.2.2 on 2026-06-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0067_securityquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='move_comments',
            field=models.JSONField(blank=True, default=list, help_text='One entry per move in solution, e.g. ["Removes the defender", "", "Forces mate"]. Use "" for moves with no comment.'),
        ),
    ]
