# Generated by Django 5.2.2 on 2026-06-18 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0068_puzzle_move_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='move_comments',
        ),
    ]
