# Generated by Django 5.2.2 on 2026-08-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0069_remove_puzzle_move_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_count', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
