# Generated by Django 5.2.2 on 2026-08-01 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0070_streak'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Streak',
        ),
    ]
